In [20]:
import numpy as np

masks = np.array([[]])

mask_zero = np.zeros(shape=(1, 20 - 10))
mask_one = np.ones(shape=(1, 10))
mask = np.concatenate([mask_zero, mask_one], axis=1)
mask_permuted = np.apply_along_axis(np.random.permutation, 1, mask)
masks = mask_permuted
masks

array([[1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
        0., 0., 1., 1.]])

In [22]:
mask_zero2 = np.zeros(shape=(1, 20 - 10))
mask_one2 = np.ones(shape=(1, 10))
mask2 = np.concatenate([mask_zero2, mask_one2], axis=1)
mask_permuted2 = np.apply_along_axis(np.random.permutation, 1, mask2)
masks = np.append(masks, mask_permuted2, axis=0)
masks

array([[1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
        0., 0., 1., 1.],
       [0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1.,
        0., 0., 0., 1.],
       [0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1.,
        0., 0., 0., 1.]])

In [42]:
import numpy as np

def get_new_random_mask():
    mask_zero =  np.zeros(shape=(1, 10))
    mask_one = np.ones(shape=(1, 10))
    mask = np.concatenate([mask_zero, mask_one], axis=1)
    mask_permuted = np.apply_along_axis(np.random.permutation, 1, mask)
    return mask_permuted

for i in range(0, 5):
    mask = get_new_random_mask()
    # if it's overlapped, again
    if i == 0:
        masks = mask
        continue
    masks = np.append(masks, mask, axis=0)

print(masks.shape)
print(masks)

(5, 20)
[[1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 0. 1.]
 [1. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0.]]


In [43]:
list = np.ones(shape=(1,10))
zeros = np.zeros(shape=(1, 10))
list = np.concatenate([list, zeros], axis=1)
list

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [44]:
applied_masks = masks * list
applied_masks

array([[1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [45]:
score = [12, 15, 2, 5, 11]

sort_idx = np.argsort(score)[::-1]
sorted_masks = applied_masks[sort_idx]
sorted_masks

array([[0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [8]:
score_list = np.array([12])
score_list = np.append(score_list, 13)
score_list = np.append(score_list, 7)
score_list

array([12, 13,  7])

In [9]:
sorted_masks[-1]

array([1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [24]:
num_mask = 20
new_mask = sorted_masks[1]
new_mask

array([1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [31]:
where_0 = np.nonzero(new_mask-1)[0]
where_0

array([ 1,  3,  4,  6,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [32]:
where_1 = np.nonzero(new_mask)[0]
where_1

array([0, 2, 5, 7, 8])

In [33]:
i0 = np.random.randint(0, len(where_0), 1)
i0

array([3])

In [35]:
new_mask[where_0[i0]]

array([1.])

In [1]:
masks_zero = np.zeros(shape=(5, 10))
masks_one = np.ones(shape=(5, 10))
masks = np.concatenate([masks_zero, masks_one], axis=1)
masks_permuted = np.apply_along_axis(np.random.permutation, 1, masks)
masks_permuted

NameError: name 'np' is not defined

In [1]:
import torch
torch.cuda.is_available()

True

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")
print(torch.version)

Using cuda device
<module 'torch.version' from '/home/somi1727/anaconda3/envs/torch/lib/python3.11/site-packages/torch/version.py'>


In [1]:
print("test", "train")

test train


In [88]:
import numpy as np
arr = np.ones(shape=(5,5))
mask = np.array([0, 1, 1, 0, 1])
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [89]:
idx = np.where(mask != 0)[1]

IndexError: tuple index out of range

In [79]:
arr[::][np.where(mask!=0)[1]]

tensor([[1., 1., 2., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [16]:
mask

array([1, 1, 1])

In [106]:
import torch
import numpy as np
arr = np.ones(shape=(6,5))
arr[1][2] = 2
arr[0][1] = 4
mask = np.array([0, 1, 1, 0, 1])
arr = torch.Tensor(arr)
mask = torch.Tensor(mask)

print(arr.shape)
print(mask.shape)
print(arr)
print(mask)

torch.Size([6, 5])
torch.Size([5])
tensor([[1., 4., 1., 1., 1.],
        [1., 1., 2., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([0., 1., 1., 0., 1.])


In [120]:
idx = torch.nonzero(mask!=0).T
idx

tensor([[1, 2, 4]])

In [119]:
arr[:, idx.T]

tensor([[[4., 1., 1.]],

        [[1., 2., 1.]],

        [[1., 1., 1.]],

        [[1., 1., 1.]],

        [[1., 1., 1.]],

        [[1., 1., 1.]]])

In [23]:
torch.mul(mask!=0, arr)

tensor([[0., 1., 1., 0., 1.],
        [0., 1., 2., 0., 1.],
        [0., 1., 1., 0., 1.],
        [0., 1., 1., 0., 1.],
        [0., 1., 1., 0., 1.],
        [0., 1., 1., 0., 1.]])

In [26]:
arr * mask[mask!=0]

RuntimeError: The size of tensor a (5) must match the size of tensor b (3) at non-singleton dimension 1

In [10]:
import torch
check = torch.nonzero(mask)
check

tensor([[1],
        [2],
        [4]])

In [16]:
torch.where(mask !=0, mask, 0)

tensor([0., 1., 1., 0., 1.])